// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"golang-rest-api-test/src/presentation/rest/controllers"
)

// Injectors from wire.go:

func ProvideController() *controllers.RootController {
	coffeeController := controllers.NewCoffeeController()
	rootController := controllers.NewRootController(coffeeController)
	return rootController
}
